      - name: Append payloads to expenses.csv (safe)
        run: |
          python - <<'PY'
          import glob, os, pathlib, sys
          root = pathlib.Path('.')
          out = root/'data'/'expenses.csv'
          out.parent.mkdir(parents=True, exist_ok=True)
          out.touch(exist_ok=True)

          files = sorted(set(glob.glob('payloads/*.csv')) |
                         set(glob.glob('payloads/**/*.csv', recursive=True)))
          print("Found payloads:", files)
          if not files:
            sys.exit(0)

          with out.open('a', encoding='utf-8', newline='') as fout:
            for fp in files:
              with open(fp, 'r', encoding='utf-8', newline='') as fin:
                txt = fin.read().rstrip('\n')
                if txt:
                  fout.write(txt + '\n')

          for fp in files:
            try: os.remove(fp)
            except: pass

          print("Appended", len(files), "file(s) into", out)
          PY
