name: Ingest Receipt Payload

on:
  push:
    branches:
      - main
    paths:
      - 'payloads/**/*.csv'         # jalan saat ada CSV baru di payloads/
  workflow_dispatch: {}              # supaya bisa Run workflow manual

jobs:
  ingest:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Append payloads to expenses.csv (safe)
        run: |
          python - <<'PY'
          import glob, os, pathlib, sys
          root = pathlib.Path('.')
          out = root/'data'/'expenses.csv'
          out.parent.mkdir(parents=True, exist_ok=True)
          out.touch(exist_ok=True)
          files = sorted(set(glob.glob('payloads/*.csv')) |
                         set(glob.glob('payloads/**/*.csv', recursive=True)))
          print("Found payloads:", files)
          if not files: sys.exit(0)
          with out.open('a', encoding='utf-8', newline='') as fout:
            for fp in files:
              with open(fp, 'r', encoding='utf-8', newline='') as fin:
                txt = fin.read().rstrip('\n')
                if txt: fout.write(txt + '\n')
          for fp in files:
            try: os.remove(fp)
            except: pass
          print("Appended", len(files), "file(s) into", out)
          PY

      - uses: actions/setup-python@v5
        with: { python-version: '3.x' }

      - name: Install deps
        run: pip install pandas matplotlib

      - name: Generate weekly report
        run: |
          python - <<'PY'
          import pandas as pd, matplotlib.pyplot as plt, pathlib
          p = pathlib.Path('data/expenses.csv')
          if not p.exists() or p.stat().st_size==0: raise SystemExit(0)
          df = pd.read_csv(p, names=['Tanggal','Toko','Kategori','Total'])
          df['Tanggal']=pd.to_datetime(df['Tanggal'], errors='coerce')
          df['Total']=pd.to_numeric(df['Total'], errors='coerce')
          df=df.dropna()
          if df.empty: raise SystemExit(0)
          w=df.groupby(pd.Grouper(key='Tanggal', freq='W'))['Total'].sum()
          plt.figure(figsize=(8,4)); w.plot(kind='bar', title='Pengeluaran Mingguan'); plt.ylabel('Total (Rp)')
          plt.tight_layout(); plt.savefig('data/weekly_report.png'); print('Saved chart')
          PY

      - name: Commit changes
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "actions@github.com"
          git add data/expenses.csv data/weekly_report.png || true
          git commit -m "Ingest receipt payload(s)" || echo "No changes"
          git push
